config/routes.rb
Rails.application.routes.draw do
  root 'main_page#index'

  get 'moja-strona', to: 'main_page#moja_strona'

  get 'kontakt', to: 'main_page#kontakt'

  get 'Ksiazki', to: 'main_books#index'

  get 'wiedzmin', to: 'main_books#wiedzmin'
  get 'mroczna_wieza', to: 'main_books#mroczna_wieza'
  get 'historia_czasu', to: 'main_books#czas'
  get 'metro', to: 'main_books#metro'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :role
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_books_controller.rb
class MainBooksController < ApplicationController
  def index

  end
  def wiedzmin

  end
  def mroczna_wieza

  end
  def metro

  end
  def czas
    
  end
end

app/controllers/main_page_controller.rb
class MainPageController < ApplicationController
  def index
    #render plain: "Hello World!"
    @my_title = "Nazwa strony"
  end
  def moja_strona

  end
  def kontakt

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_books_helper.rb
module MainBooksHelper
end

app/helpers/main_page_helper.rb
module MainPageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Www</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main_books/czas.html.erb
Tu będzie znajdowała książka

app/views/main_books/index.html.erb
<h1>Książki</h1>
<ol>
  <li><%= link_to 'Wiedźmin Andrzej Sapkowski', wiedzmin_path %></li>
  <li><%= link_to 'Mroczna Wieża Stephen King',  mroczna_wieza_path%></li>
  <li><%= link_to 'Krótka historia czasu Stephen Hawking',historia_czasu_path %></li>
  <li><%= link_to 'Metro 2033 Dmitry Glukhovsky', metro_path %></li>
</ol>

app/views/main_books/metro.html.erb
Tu będzie znajdowała książka

app/views/main_books/mroczna_wieza.html.erb
Tu będzie znajdowała książka

app/views/main_books/wiedzmin.html.erb
Tu będzie znajdowała książka

app/views/main_page/index.html.erb
<%=@my_title%>
<h2>Test html</h2>
<p>nie ma render</p>

app/views/main_page/kontakt.html.erb
<style>
    body
    {
        background-color: #000000;
        color: #FFFFFF;

    }
    h1
    {
        text-align: center;
    }
    #container
    {
        width: 1000px;
        margin: 0 auto;
        border: #999999 solid 2px;
        height: 200px;
        padding: 20px;
    }
    #tresc
    {
        width: 870px;
        float: left;

    }
    #link
    {
        width: 120px;
        float: left;
        height: 200px;
        border-left: #999999 solid 1px;
    }
    #email
    {
        margin-left: 100px;
    }
</style>
<body>
<div id="container">
  <div id="tresc">
    <h1>Kontakt</h1>
    <div id="email">
        <p>
          Zapraszam do kontaktu:
        </p>
        <p>
          kapikap1@live.com
        </p>
    </div>
    <br>
  </div>

  <div id="link">
    <h1>Menu</h1>
    <ul>
      <li>  <%= link_to "Moja strona", moja_strona_path %></li>
      <li>  <%= link_to "Kontakt", kontakt_path  %></li>
    </ul>
  </div>


</div>
</body>


app/views/main_page/moja_strona.html.erb
<style>
  body
  {
      background-color: #000000;
      color: #FFFFFF;

  }
  h1
  {
      text-align: center;
  }
  #container
  {
      width: 1000px;
      margin: 0 auto;
      border: #999999 solid 2px;
      height: 200px;
      padding: 20px;
  }
  #tresc
  {
      width: 870px;
      float: left;

  }
  #link
  {
       width: 120px;
       float: left;
      height: 200px;
      border-left: #999999 solid 1px;
  }

</style>
<body>
  <div id="container">
    <div id="tresc">
      <h1>Moja Strona</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sagittis sollicitudin hendrerit.
        Donec nec interdum leo. Aliquam quis leo at sapien sodales semper. Morbi non dictum libero, in hendrerit erat.
        Donec sagittis elementum consectetur. Phasellus tincidunt ultricies magna, vel aliquam dolor molestie non.
        Proin enim orci, vulputate condimentum bibendum nec, congue vitae lacus. Mauris laoreet est eros,
        non tempus tortor vestibulum ullamcorper. Nunc luctus nibh in massa dapibus hendrerit.
        Cras tempus magna ac ex ullamcorper, quis consequat lectus efficitur. Integer auctor viverra mi in tempus.
      </p>
      <br>
    </div>

    <div id="link">
      <h1>Menu</h1>
      <ul>
        <li>  <%= link_to "Moja strona", moja_strona_path %></li>
        <li>  <%= link_to "Kontakt", kontakt_path  %></li>
      </ul>
    </div>


  </div>
</body>
